// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	api/auth/auth.proto

It has these top-level messages:
	LoginKeyReq
	LoginResp
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginKeyReq struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *LoginKeyReq) Reset()                    { *m = LoginKeyReq{} }
func (m *LoginKeyReq) String() string            { return proto.CompactTextString(m) }
func (*LoginKeyReq) ProtoMessage()               {}
func (*LoginKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginKeyReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LoginResp struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResp) Reset()                    { *m = LoginResp{} }
func (m *LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()               {}
func (*LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginKeyReq)(nil), "auth.LoginKeyReq")
	proto.RegisterType((*LoginResp)(nil), "auth.LoginResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	// Login using private key.
	//
	// Login using private key.
	LoginKey(ctx context.Context, in *LoginKeyReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) LoginKey(ctx context.Context, in *LoginKeyReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := grpc.Invoke(ctx, "/auth.Auth/LoginKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	// Login using private key.
	//
	// Login using private key.
	LoginKey(context.Context, *LoginKeyReq) (*LoginResp, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_LoginKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/LoginKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginKey(ctx, req.(*LoginKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginKey",
			Handler:    _Auth_LoginKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/auth.proto",
}

func init() { proto.RegisterFile("api/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0x2d, 0xc9, 0x00, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6,
	0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x45, 0x5e, 0x5e, 0x7e, 0x49, 0x62,
	0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x8d, 0x92, 0x3c, 0x17, 0xb7, 0x4f, 0x7e, 0x7a, 0x66, 0x9e,
	0x77, 0x6a, 0x65, 0x50, 0x6a, 0xa1, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0xa4, 0xc8, 0xc5, 0x09, 0x56, 0x10, 0x94, 0x5a, 0x5c, 0x20,
	0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d, 0x9a, 0x07, 0x55, 0x00, 0xe1, 0x18, 0x85, 0x70, 0xb1,
	0x38, 0x96, 0x96, 0x64, 0x08, 0xf9, 0x70, 0x71, 0xc0, 0xcc, 0x12, 0x12, 0xd4, 0x03, 0x3b, 0x04,
	0xc9, 0x6c, 0x29, 0x7e, 0x24, 0x21, 0x90, 0x69, 0x4a, 0x32, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x12,
	0x53, 0x12, 0xd4, 0x2f, 0x33, 0x84, 0x38, 0x3e, 0x07, 0xaa, 0xdc, 0x8a, 0x51, 0x2b, 0x89, 0x0d,
	0xec, 0x40, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x6d, 0x12, 0x0c, 0xdb, 0x00, 0x00,
	0x00,
}
